# theme: minima
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: My Awesome Site
description: This is my GitHub Pages site using Jekyll.
url: https://dcurran90.github.io
# baseurl: ""